"""
Generate a brief methods summary for AirLock output.
This text is intended for inclusion in reports or publications
and describes how postcode-to-grid matching was performed.
"""

from datetime import datetime, UTC


def generate_methods_summary(
    nox_rows: int,
    postcode_rows: int,
    matched_rows: int,
    unmatched_rows: int,
    match_rate: float,
) -> str:
    """
    Create a plain-text methods summary that describes:

    - Data sources used
    - CRS (OSGB36)
    - Grid construction (1km squares from centre points)
    - Point-in-polygon matching process
    - Validation steps
    """

    # Updated to modern timezone-aware UTC timestamp
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    summary = f"""
AirLock – Methods Summary
Generated: {timestamp}

1. Data Sources
---------------
• DEFRA Pollution Climate Mapping (PCM) 1 km grid dataset.
  The dataset provides OSGB36 Easting (X) and Northing (Y)
  coordinates representing the centre of each grid cell.
• ONS Postcode Directory (ONSPD), which includes postcode
  coordinates as Eastings (oseast1m) and Northings (osnrth1m)
  in OSGB36.

2. Coordinate System
--------------------
• All spatial processing was performed in British National Grid
  (OSGB36), EPSG:27700.
• Units are metres. No reprojection was required.

3. Grid Cell Construction
-------------------------
• Each NOx grid cell was reconstructed as a 1 km × 1 km polygon
  by expanding 500 metres in each direction from the provided
  (X, Y) centre coordinates.

4. Postcode Geometry
--------------------
• Postcodes were converted into point geometries using their
  OSGB36 Easting/Northing fields.
• Postcodes with missing or invalid coordinates were excluded.

5. Matching Method
------------------
• A spatial point-in-polygon join was performed.
  Each postcode point was assigned to the grid cell polygon
  that contained it.
• GeoPandas spatial index (R-tree) was used to improve
  performance on large datasets.

6. Validation
-------------
• Required fields were checked for both datasets.
• Coordinate ranges were validated against typical OSGB36 bounds.
• Rows with invalid coordinates were skipped.

7. Summary Statistics
---------------------
Total NOx grid cells loaded: {nox_rows}
Total postcode records processed: {postcode_rows}
Matched postcodes: {matched_rows}
Unmatched postcodes: {unmatched_rows}
Match rate: {match_rate:.2%}

This methods summary was automatically generated by AirLock.
"""

    return summary.strip()
